#!/bin/bash

# Build docker images
echo "### Building images ###"
docker-compose build

echo "### Starting containers ###"
docker-compose up -d

if [ ! -f .env ]; then
    echo "### Creating .env file ###"
    cp .env.example .env
fi

# NPM dependencies
echo "### Installing npm dependencies ###"
./run npm install

echo "### Installing composer dependencies ###"
./run composer install

# Application setup
echo "### Application setup ###"
./run php artisan key:generate
./run php artisan migrate:reset
./run php artisan migrate

echo "### Running tests ###"
./run vendor/bin/phpunit -c phpunit.xml

echo "### Clearing database ###"
./run php artisan migrate:reset
./run php artisan migrate

echo "### DONE! ###"
echo ""
echo "Run ./up to start the application"